package theme

// This file is generated by nord_colors_generator.go
// Please do not edit manually, use:
// go generate ./theme/...
//
// The colors are taken from: https://www.nordtheme.com/docs/colors-and-palettes

import (
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/theme"
)

var nordDarkScheme = map[fyne.ThemeColorName]color.Color{
	theme.ColorBlue:                  color.RGBA{0x81, 0xa1, 0xc1, 0xff}, // Nord color name @nord9
	theme.ColorBrown:                 color.RGBA{0x4c, 0x56, 0x6a, 0xff}, // Nord color name @nord3
	theme.ColorGray:                  color.RGBA{0xd8, 0xde, 0xe9, 0xff}, // Nord color name @nord4
	theme.ColorGreen:                 color.RGBA{0xa3, 0xbe, 0x8c, 0xff}, // Nord color name @nord14
	theme.ColorNameBackground:        color.RGBA{0x2e, 0x34, 0x40, 0xff}, // Nord color name @nord0
	theme.ColorNameButton:            color.RGBA{0x3b, 0x42, 0x52, 0xff}, // Nord color name @nord1
	theme.ColorNameError:             color.RGBA{0xbf, 0x61, 0x6a, 0xff}, // Nord color name @nord11
	theme.ColorNameForeground:        color.RGBA{0xec, 0xef, 0xf4, 0xff}, // Nord color name @nord6
	theme.ColorNameInputBackground:   color.RGBA{0x3b, 0x42, 0x52, 0xff}, // Nord color name @nord1
	theme.ColorNameMenuBackground:    color.RGBA{0x3b, 0x42, 0x52, 0xff}, // Nord color name @nord1
	theme.ColorNameOverlayBackground: color.RGBA{0x3b, 0x42, 0x52, 0xff}, // Nord color name @nord1
	theme.ColorNamePrimary:           color.RGBA{0x88, 0xc0, 0xd0, 0xff}, // Nord color name @nord8
	theme.ColorNameSelection:         color.RGBA{0x4c, 0x56, 0x6a, 0xff}, // Nord color name @nord3
	theme.ColorNameShadow:            color.RGBA{0x00, 0x00, 0x00, 0x5b}, // Nord color name @dark0
	theme.ColorNameSuccess:           color.RGBA{0xa3, 0xbe, 0x8c, 0xff}, // Nord color name @nord14
	theme.ColorNameWarning:           color.RGBA{0xd0, 0x87, 0x70, 0xff}, // Nord color name @nord12
	theme.ColorOrange:                color.RGBA{0xd0, 0x87, 0x70, 0xff}, // Nord color name @nord12
	theme.ColorPurple:                color.RGBA{0xb4, 0x8e, 0xad, 0xff}, // Nord color name @nord15
	theme.ColorRed:                   color.RGBA{0xbf, 0x61, 0x6a, 0xff}, // Nord color name @nord11
	theme.ColorYellow:                color.RGBA{0xeb, 0xcb, 0x8b, 0xff}, // Nord color name @nord13
}

var nordLightScheme = map[fyne.ThemeColorName]color.Color{
	theme.ColorBlue:                  color.RGBA{0x81, 0xa1, 0xc1, 0xff}, // Nord color name @nord9
	theme.ColorBrown:                 color.RGBA{0x4c, 0x56, 0x6a, 0xff}, // Nord color name @nord3
	theme.ColorGray:                  color.RGBA{0xd8, 0xde, 0xe9, 0xff}, // Nord color name @nord4
	theme.ColorGreen:                 color.RGBA{0xa3, 0xbe, 0x8c, 0xff}, // Nord color name @nord14
	theme.ColorNameBackground:        color.RGBA{0xec, 0xef, 0xf4, 0xff}, // Nord color name @nord6
	theme.ColorNameButton:            color.RGBA{0xd8, 0xde, 0xe9, 0xff}, // Nord color name @nord4
	theme.ColorNameError:             color.RGBA{0xbf, 0x61, 0x6a, 0xff}, // Nord color name @nord11
	theme.ColorNameForeground:        color.RGBA{0x2e, 0x34, 0x40, 0xff}, // Nord color name @nord0
	theme.ColorNameInputBackground:   color.RGBA{0xe5, 0xe9, 0xf0, 0xff}, // Nord color name @nord5
	theme.ColorNameMenuBackground:    color.RGBA{0xe5, 0xe9, 0xf0, 0xff}, // Nord color name @nord5
	theme.ColorNameOverlayBackground: color.RGBA{0xe5, 0xe9, 0xf0, 0xff}, // Nord color name @nord5
	theme.ColorNamePrimary:           color.RGBA{0x8f, 0xbc, 0xbb, 0xff}, // Nord color name @nord7
	theme.ColorNameSelection:         color.RGBA{0x8f, 0xbc, 0xbb, 0xff}, // Nord color name @nord7
	theme.ColorNameShadow:            color.RGBA{0x00, 0x04, 0x00, 0x11}, // Nord color name @dark1
	theme.ColorNameSuccess:           color.RGBA{0xa3, 0xbe, 0x8c, 0xff}, // Nord color name @nord14
	theme.ColorNameWarning:           color.RGBA{0xd0, 0x87, 0x70, 0xff}, // Nord color name @nord12
	theme.ColorOrange:                color.RGBA{0xd0, 0x87, 0x70, 0xff}, // Nord color name @nord12
	theme.ColorPurple:                color.RGBA{0xb4, 0x8e, 0xad, 0xff}, // Nord color name @nord15
	theme.ColorRed:                   color.RGBA{0xbf, 0x61, 0x6a, 0xff}, // Nord color name @nord11
	theme.ColorYellow:                color.RGBA{0xeb, 0xcb, 0x8b, 0xff}, // Nord color name @nord13
}
